# Generated by Django 5.1.7 on 2025-04-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('provider', models.CharField(max_length=100)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
